apiVersion: v1
entries:
  bundle-generator-service:
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2023-07-21T17:21:27.266058364Z"
    description: Bundle Generator service
    digest: 8b086ed0cca5e15114bf1eb28c47a0d25b3cf32bb39523844997ea4791b97873
    kubeVersion: '>=1.12.0-0'
    name: bundle-generator-service
    type: application
    urls:
    - https://libertyglobal.github.io/bundle-generator-service/charts/bundle-generator-service-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2023-07-21T17:21:27.265538457Z"
    description: Bundle Generator service
    digest: 30c799c07db53f1f031e789a2a91bf9576cc6576cfbae5883bac039270f814da
    kubeVersion: '>=1.12.0-0'
    name: bundle-generator-service
    type: application
    urls:
    - https://libertyglobal.github.io/bundle-generator-service/charts/bundle-generator-service-0.0.17.tgz
    version: 0.0.17
generated: "2023-07-21T17:21:27.264835248Z"
