configMap:
  APP: bundle-generator-service

service:
  type: "ClusterIP"
  port: 80
  containerPort: 8081

image:
  repository: daccloud/bundle-generator-service

pv:
  path: /bundle-generator-bundlegen/data
  server: <ip address of nfs>