name: Builds the project
on:
  workflow_call:
    inputs:
      version:
        description: "Version to build"
        type: string
        required: true
      pushDockerImage:
        description: "Push docker image"
        default: false
        type: boolean
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_SERVICE_IMAGE_NAME: bundle-generator-service
  DOCKER_BUNDLEGEN_IMAGE_NAME: bundle-generator-bundlegen

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          sed -i 's|^version = .*|version = '"'${{ inputs.version }}'"'|g' service/pyproject.toml
          sed -i 's|version=.*|version='"'${{ inputs.version }}'"',|g' BundleGen/setup.py
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.DOCKER_SERVICE_IMAGE_NAME }}:${{ inputs.version }} ./service
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.DOCKER_BUNDLEGEN_IMAGE_NAME }}:${{ inputs.version }} -f ./BundleGen/docker/rabbitmq/Dockerfile ./BundleGen
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push
        if: inputs.pushDockerImage == true
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.DOCKER_SERVICE_IMAGE_NAME }}:${{ inputs.version }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.DOCKER_BUNDLEGEN_IMAGE_NAME }}:${{ inputs.version }}
